# author: Conner Ohnesorge 
# Syncronizes the kanban tracking the entirety of the project onto github projects.
# Intended to sync the Github Project As a database to add to on a build
name: Add Skill's and Categorized
# makes the name `Add Skills's And Categorized`
on:
    page_build: 
        types: [created]
jobs:
    remove_skills:
        runs-on: ubuntu-latest
        # Makes the system an ubuntu with the latest distribution
        steps:
        - name: get-skills-
          env:
            GITHUB_TOKEN: ${{ secrets.YOUR_TOKEN }}
            ORGANIZATION: YOUR_ORGANIZATION
            PROJECT_NUMBER: YOUR_PROJECT_NUMBER
          run: |
            echo "incomplete github action"
